import type { ExposedDataType, ExposureSourceType, RemediationState } from "./exposure";

/**
 * Remediation (spec 7.7, 13.6). User-driven, separate from detection state.
 * Transitions are explicit; anything not listed is rejected.
 *
 *   open ──▶ in_progress ──▶ remediated
 *     │          │    ▲            │
 *     ├──────────┼────┘ (reopen)   │
 *     ▼          ▼                 ▼
 *   dismissed ◀──────────── (reopen to open)
 */
const EDGES: Record<RemediationState, readonly RemediationState[]> = {
  open: ["in_progress", "remediated", "dismissed"],
  in_progress: ["open", "remediated", "dismissed"],
  remediated: ["in_progress", "open"],
  dismissed: ["open"],
};

export function canTransitionRemediation(from: RemediationState, to: RemediationState): boolean {
  return EDGES[from].includes(to);
}

export const DISMISS_REASONS = ["not_my_account", "already_handled", "account_closed", "other"] as const;
export type DismissReason = (typeof DISMISS_REASONS)[number];

export const DISMISS_REASON_LABELS: Record<DismissReason, string> = {
  not_my_account: "I never had an account there",
  already_handled: "I already dealt with this",
  account_closed: "The account is closed",
  other: "Other",
};

export interface ChecklistItem {
  key: ChecklistKey;
  label: string;
  description: string;
}

export const CHECKLIST_KEYS = [
  "clean-device",
  "change-password",
  "update-reused-passwords",
  "enable-mfa",
  "change-security-questions",
  "review-account-activity",
  "watch-financial-statements",
  "protect-identity",
  "secure-phone-number",
  "watch-phishing",
] as const;
export type ChecklistKey = (typeof CHECKLIST_KEYS)[number];

const ITEMS: Record<ChecklistKey, Omit<ChecklistItem, "key">> = {
  "clean-device": {
    label: "Scan the infected device for malware",
    description:
      "Malware logs come from an infected computer or phone. Clean it before changing passwords on it.",
  },
  "change-password": {
    label: "Change the password for this account",
    description: "Use a new, unique password, ideally generated by a password manager.",
  },
  "update-reused-passwords": {
    label: "Change it anywhere you reused it",
    description: "Attackers try leaked passwords on other sites. Every account should have its own.",
  },
  "enable-mfa": {
    label: "Turn on two-factor authentication",
    description: "An authenticator app or passkey stops sign-ins that only have your password.",
  },
  "change-security-questions": {
    label: "Change your security questions and answers",
    description: "Exposed answers can be used to reset your password. Treat them like passwords.",
  },
  "review-account-activity": {
    label: "Review recent account activity",
    description: "Check sign-ins, connected devices and recovery settings for anything you don't recognise.",
  },
  "watch-financial-statements": {
    label: "Check bank and card statements",
    description: "Report unfamiliar charges to your bank; consider replacing the card.",
  },
  "protect-identity": {
    label: "Guard against identity fraud",
    description:
      "Consider a credit freeze or fraud alert where available, and watch for accounts you didn't open.",
  },
  "secure-phone-number": {
    label: "Protect your phone number",
    description: "Ask your carrier for a port-out PIN, and never share codes sent by text.",
  },
  "watch-phishing": {
    label: "Be alert to targeted phishing",
    description:
      "Exposed details make scam emails more convincing. Don't follow links in unexpected messages.",
  },
};

const PASSWORDS: readonly ExposedDataType[] = ["password_plaintext", "password_hash", "auth_token"];

/**
 * The checklist for one exposure, built from what was actually exposed. Pure
 * and deterministic: the keys are stable, so saved progress survives reloads.
 */
export function getRemediationChecklist(exposure: {
  dataTypes: readonly ExposedDataType[];
  sourceType: ExposureSourceType;
}): ChecklistItem[] {
  const has = (...types: ExposedDataType[]) => exposure.dataTypes.some((t) => types.includes(t));
  const keys: ChecklistKey[] = [];
  if (exposure.sourceType === "stealer_log") keys.push("clean-device");
  if (has(...PASSWORDS) || exposure.sourceType === "stealer_log") {
    keys.push("change-password", "update-reused-passwords", "enable-mfa");
  }
  if (has("security_qa")) keys.push("change-security-questions");
  keys.push("review-account-activity");
  if (has("financial")) keys.push("watch-financial-statements");
  if (has("government_id") || (has("date_of_birth") && has("physical_address")))
    keys.push("protect-identity");
  if (has("phone")) keys.push("secure-phone-number");
  if (!has(...PASSWORDS)) keys.push("watch-phishing");
  return keys.map((key) => ({ key, ...ITEMS[key] }));
}

/**
 * Remediation state implied by checklist progress (D-031):
 * all done → remediated; some done → in_progress; none → open.
 * A dismissed exposure stays dismissed until the user reopens it.
 */
export function stateFromChecklist(current: RemediationState, done: number, total: number): RemediationState {
  if (current === "dismissed") return "dismissed";
  if (total > 0 && done >= total) return "remediated";
  if (done > 0) return "in_progress";
  return current === "remediated" || current === "in_progress" ? "open" : current;
}

/** Categories worth telling the user were NOT reported (spec 13.6 "Not detected"). */
export const NOTABLE_CATEGORIES: readonly ExposedDataType[] = [
  "email",
  "password_plaintext",
  "password_hash",
  "auth_token",
  "security_qa",
  "financial",
  "government_id",
  "physical_address",
  "phone",
  "date_of_birth",
];
